-- To select Ai_tools_db
use ai_tools_db;

-- Table 1 = ai_tools

CREATE TABLE ai_tools (
    name VARCHAR(120) NOT NULL,
    description TEXT NOT NULL,
    category VARCHAR(80) NOT NULL,
    url VARCHAR(255) NOT NULL,
    tags VARCHAR(255) NULL DEFAULT NULL,
    pricing VARCHAR(50) NULL DEFAULT 'Free',
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    logo VARCHAR(255) NULL DEFAULT NULL
);

-- Table 2 = Users

CREATE TABLE users (
    username VARCHAR(100) NOT NULL,
    email VARCHAR(120) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

-- Inserting tools into ai_tools table

INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('ChatGPT', 'AI assistant for writing, coding, research and brainstorming.', 'Writing', 'https://chatgpt.com', 'chatbot,gpt,writing,coding', 'Freemium', '2026-07-01 13:37:32', 'chatgpt.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Claude', 'AI assistant for document analysis and coding.', 'Writing', 'https://claude.ai', 'writing,analysis,chatbot', 'Freemium', '2026-07-01 13:37:32', 'claude.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Gemini', 'Google AI assistant for writing and productivity.', 'Writing', 'https://gemini.google.com', 'google,assistant,writing', 'Freemium', '2026-07-01 13:37:32', 'gemini.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Microsoft Copilot', 'AI assistant integrated with Microsoft products.', 'Productivity', 'https://copilot.microsoft.com', 'office,coding,assistant', 'Freemium', '2026-07-01 13:37:32', 'copilot.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Perplexity AI', 'AI search engine with cited answers.', 'Search', 'https://www.perplexity.ai', 'search,research,ai', 'Freemium', '2026-07-01 13:37:32', 'perplexity.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Grok', 'AI chatbot developed by xAI.', 'Chatbot', 'https://grok.com', 'chatbot,xai', 'Freemium', '2026-07-01 13:37:32', 'grok.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Poe', 'Access multiple AI models in one place.', 'Chatbot', 'https://poe.com', 'chatbot,llm', 'Freemium', '2026-07-01 13:37:32', 'poe.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Jasper', 'AI content writer for businesses and marketers.', 'Writing', 'https://www.jasper.ai', 'copywriting,marketing', 'Paid', '2026-07-01 13:37:32', 'jasper.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Copy.ai', 'Generate marketing copy using AI.', 'Marketing', 'https://www.copy.ai', 'copywriting,marketing', 'Freemium', '2026-07-01 13:37:32', 'copyai.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Writesonic', 'AI writing assistant for blogs and ads.', 'Writing', 'https://writesonic.com', 'blog,seo,writing', 'Freemium', '2026-07-01 13:37:32', 'writesonic.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Rytr', 'Affordable AI writing assistant.', 'Writing', 'https://rytr.me', 'writing,blog', 'Freemium', '2026-07-01 13:37:32', 'rytr.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Grammarly', 'AI grammar and writing assistant.', 'Writing', 'https://www.grammarly.com', 'grammar,editing', 'Freemium', '2026-07-01 13:37:32', 'grammarly.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Notion AI', 'AI-powered writing inside Notion.', 'Productivity', 'https://www.notion.so/product/ai', 'notes,writing', 'Freemium', '2026-07-01 13:37:32', 'notion-ai.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('QuillBot', 'AI paraphrasing and grammar tool.', 'Writing', 'https://quillbot.com', 'paraphrase,grammar', 'Freemium', '2026-07-01 13:37:32', 'quillbot.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Sudowrite', 'AI creative writing assistant.', 'Writing', 'https://www.sudowrite.com', 'stories,creative', 'Paid', '2026-07-01 13:37:32', 'sudowrite.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Wordtune', 'Rewrite and improve sentences.', 'Writing', 'https://www.wordtune.com', 'rewrite,editing', 'Freemium', '2026-07-01 13:37:32', 'wordtune.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('HyperWrite', 'AI writing companion for emails and documents.', 'Writing', 'https://www.hyperwriteai.com', 'emails,writing', 'Freemium', '2026-07-01 13:37:32', 'hyperwrite.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Anyword', 'AI copywriting optimized for conversions.', 'Marketing', 'https://anyword.com', 'ads,copywriting', 'Paid', '2026-07-01 13:37:32', 'anyword.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Simplified AI', 'AI content creation platform.', 'Marketing', 'https://simplified.com', 'content,social', 'Freemium', '2026-07-01 13:37:32', 'simplified.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Frase', 'AI SEO content optimization.', 'SEO', 'https://www.frase.io', 'seo,content', 'Paid', '2026-07-01 13:37:32', 'frase.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Surfer SEO', 'AI-powered SEO optimization tool.', 'SEO', 'https://surferseo.com', 'seo,blogs', 'Paid', '2026-07-01 13:37:32', 'surfer-seo.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Scalenut', 'AI SEO and content platform.', 'SEO', 'https://www.scalenut.com', 'seo,content', 'Freemium', '2026-07-01 13:37:32', 'scalenut.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('NeuronWriter', 'SEO writing assistant.', 'SEO', 'https://neuronwriter.com', 'seo,writing', 'Paid', '2026-07-01 13:37:32', 'neuronwriter.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('INK', 'AI content and SEO assistant.', 'SEO', 'https://inkforall.com', 'seo,writing', 'Freemium', '2026-07-01 13:37:32', 'ink.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('LongShot AI', 'Long-form AI writing tool.', 'Writing', 'https://longshot.ai', 'blogs,articles', 'Freemium', '2026-07-01 13:37:32', 'longshot.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('DeepL Write', 'AI writing improvement tool.', 'Writing', 'https://www.deepl.com/write', 'grammar,rewrite', 'Free', '2026-07-01 13:37:32', 'deepl-write.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('DeepL Translator', 'AI language translation service.', 'Translation', 'https://www.deepl.com', 'translate,languages', 'Freemium', '2026-07-01 13:37:32', 'deepl.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Google Translate', 'AI-powered language translator.', 'Translation', 'https://translate.google.com', 'translation,languages', 'Free', '2026-07-01 13:37:32', 'google-translate.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('ElevenLabs', 'AI voice generation platform.', 'Voice', 'https://elevenlabs.io', 'voice,text-to-speech', 'Freemium', '2026-07-01 13:37:32', 'elevenlabs.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Murf AI', 'Professional AI voice generator.', 'Voice', 'https://murf.ai', 'voice,narration', 'Freemium', '2026-07-01 13:37:32', 'murf.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Speechify', 'Convert text into natural speech.', 'Voice', 'https://speechify.com', 'tts,audio', 'Freemium', '2026-07-01 13:37:32', 'speechify.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('PlayHT', 'Realistic AI text-to-speech platform.', 'Voice', 'https://play.ht', 'tts,voice', 'Freemium', '2026-07-01 13:37:32', 'playht.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('LOVO AI', 'AI voiceover generator.', 'Voice', 'https://lovo.ai', 'voiceover,tts', 'Freemium', '2026-07-01 13:37:32', 'lovo.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Resemble AI', 'Custom AI voice cloning platform.', 'Voice', 'https://www.resemble.ai', 'voice,clone', 'Paid', '2026-07-01 13:37:32', 'resemble.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Otter.ai', 'AI meeting transcription assistant.', 'Productivity', 'https://otter.ai', 'meetings,transcription', 'Freemium', '2026-07-01 13:37:32', 'otter.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Fireflies.ai', 'Meeting recording and AI notes.', 'Productivity', 'https://fireflies.ai', 'meeting,notes', 'Freemium', '2026-07-01 13:37:32', 'fireflies.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Fathom', 'Free AI meeting assistant.', 'Productivity', 'https://fathom.video', 'meetings,zoom', 'Free', '2026-07-01 13:37:32', 'fathom.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('tl;dv', 'AI meeting summaries.', 'Productivity', 'https://tldv.io', 'meeting,summary', 'Freemium', '2026-07-01 13:37:32', 'tldv.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('AssemblyAI', 'Speech recognition API.', 'Developer', 'https://www.assemblyai.com', 'speech,api', 'Paid', '2026-07-01 13:37:32', 'assemblyai.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('OpenAI Whisper', 'Open-source speech recognition model.', 'Developer', 'https://openai.com/index/whisper', 'speech,transcription', 'Open Source', '2026-07-01 13:37:32', 'whisper.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Descript', 'Edit audio and video using AI.', 'Audio', 'https://www.descript.com', 'editing,podcast', 'Freemium', '2026-07-01 13:37:32', 'descript.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Krisp', 'Remove background noise using AI.', 'Audio', 'https://krisp.ai', 'noise,audio', 'Freemium', '2026-07-01 13:37:32', 'krisp.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Adobe Podcast', 'AI audio enhancement platform.', 'Audio', 'https://podcast.adobe.com', 'podcast,audio', 'Free', '2026-07-01 13:37:32', 'adobe-podcast.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Cleanvoice AI', 'Remove filler words from recordings.', 'Audio', 'https://cleanvoice.ai', 'podcast,editing', 'Paid', '2026-07-01 13:37:32', 'cleanvoice.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('AIVA', 'AI music composer.', 'Music', 'https://www.aiva.ai', 'music,composer', 'Freemium', '2026-07-01 13:37:32', 'aiva.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Suno', 'Generate complete songs using AI.', 'Music', 'https://suno.com', 'music,songs', 'Freemium', '2026-07-01 13:37:32', 'suno.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Udio', 'AI music generation platform.', 'Music', 'https://udio.com', 'music,audio', 'Freemium', '2026-07-01 13:37:32', 'udio.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Boomy', 'Create AI music instantly.', 'Music', 'https://boomy.com', 'music,creator', 'Freemium', '2026-07-01 13:37:32', 'boomy.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Soundraw', 'Royalty-free AI music generator.', 'Music', 'https://soundraw.io', 'music,background', 'Paid', '2026-07-01 13:37:32', 'soundraw.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Beatoven AI', 'AI-generated background music.', 'Music', 'https://www.beatoven.ai', 'music,video', 'Freemium', '2026-07-01 13:37:32', 'beatoven.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Midjourney', 'AI image generator that creates artistic images from text prompts.', 'Image Generation', 'https://www.midjourney.com', 'image,art,generator', 'Paid', '2026-07-01 13:38:33', 'midjourney.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('DALL·E', 'OpenAI image generation model for creating images from text.', 'Image Generation', 'https://chatgpt.com/images', 'image,art,generator', 'Freemium', '2026-07-01 13:38:33', 'dalle.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Leonardo AI', 'AI image generator for game assets and artwork.', 'Image Generation', 'https://leonardo.ai', 'image,design,art', 'Freemium', '2026-07-01 13:38:33', 'leonardo.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Adobe Firefly', 'Adobe AI for image generation and editing.', 'Image Generation', 'https://firefly.adobe.com', 'adobe,image,design', 'Freemium', '2026-07-01 13:38:33', 'firefly.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Canva Magic Studio', 'AI-powered design assistant inside Canva.', 'Design', 'https://www.canva.com/magic-studio', 'design,presentation,image', 'Freemium', '2026-07-01 13:38:33', 'canva.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Ideogram', 'Generate images with accurate text rendering.', 'Image Generation', 'https://ideogram.ai', 'image,text,design', 'Freemium', '2026-07-01 13:38:33', 'ideogram.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Stable Diffusion', 'Open-source AI image generation model.', 'Image Generation', 'https://stability.ai', 'image,open-source', 'Open Source', '2026-07-01 13:38:33', 'stable-diffusion.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Playground AI', 'AI image creation and editing platform.', 'Image Generation', 'https://playground.com', 'image,art', 'Freemium', '2026-07-01 13:38:33', 'playground.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('DreamStudio', 'Official Stable Diffusion image generator.', 'Image Generation', 'https://dreamstudio.ai', 'image,art', 'Freemium', '2026-07-01 13:38:33', 'dreamstudio.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('FLUX.1', 'State-of-the-art image generation model by Black Forest Labs.', 'Image Generation', 'https://blackforestlabs.ai', 'image,ai', 'Freemium', '2026-07-01 13:38:33', 'flux.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Mage Space', 'Free AI image generator using Stable Diffusion.', 'Image Generation', 'https://www.mage.space', 'image,art', 'Freemium', '2026-07-01 13:38:33', 'mage-space.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('NightCafe', 'AI art generator supporting multiple models.', 'Image Generation', 'https://creator.nightcafe.studio', 'art,image', 'Freemium', '2026-07-01 13:38:33', 'nightcafe.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Lexica', 'Search and generate Stable Diffusion images.', 'Image Generation', 'https://lexica.art', 'image,prompts', 'Freemium', '2026-07-01 13:38:33', 'lexica.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('BlueWillow', 'AI image generator for creative artwork.', 'Image Generation', 'https://www.bluewillow.ai', 'image,creative', 'Free', '2026-07-01 13:38:33', 'bluewillow.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('CF Spark', 'AI image generator by Creative Fabrica.', 'Image Generation', 'https://www.creativefabrica.com/spark', 'image,design', 'Freemium', '2026-07-01 13:38:33', 'cf-spark.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Runway', 'AI video editing and generation platform.', 'Video Generation', 'https://runwayml.com', 'video,editing', 'Freemium', '2026-07-01 13:38:33', 'runway.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Pika', 'Generate videos from text prompts.', 'Video Generation', 'https://pika.art', 'video,generator', 'Freemium', '2026-07-01 13:38:33', 'pika.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Luma Dream Machine', 'AI video generation platform by Luma AI.', 'Video Generation', 'https://lumalabs.ai/dream-machine', 'video,3d', 'Freemium', '2026-07-01 13:38:33', 'luma.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Kling AI', 'AI video generation model.', 'Video Generation', 'https://klingai.com', 'video,animation', 'Freemium', '2026-07-01 13:38:33', 'kling.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Google Veo', 'Google AI video generation model.', 'Video Generation', 'https://deepmind.google/models/veo', 'video,google', 'Limited', '2026-07-01 13:38:33', 'veo.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Synthesia', 'Create AI avatar videos from text.', 'Video Generation', 'https://www.synthesia.io', 'avatar,video', 'Paid', '2026-07-01 13:38:33', 'synthesia.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('HeyGen', 'AI talking avatar video generator.', 'Video Generation', 'https://www.heygen.com', 'avatar,video', 'Freemium', '2026-07-01 13:38:33', 'heygen.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('InVideo AI', 'AI-powered online video creator.', 'Video Generation', 'https://invideo.io', 'video,editing', 'Freemium', '2026-07-01 13:38:33', 'invideo.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Kapwing AI', 'AI video editing and subtitle generator.', 'Video Generation', 'https://www.kapwing.com', 'video,editing', 'Freemium', '2026-07-01 13:38:33', 'kapwing.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('CapCut AI', 'AI-powered video editing tools.', 'Video Generation', 'https://www.capcut.com', 'video,editing', 'Free', '2026-07-01 13:38:33', 'capcut.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Animoto', 'AI-assisted online video maker.', 'Video Generation', 'https://animoto.com', 'video,marketing', 'Freemium', '2026-07-01 13:38:33', 'animoto.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Steve AI', 'Create animated videos using AI.', 'Animation', 'https://www.steve.ai', 'animation,video', 'Freemium', '2026-07-01 13:38:33', 'steve-ai.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Elai.io', 'AI presenter video creation platform.', 'Video Generation', 'https://elai.io', 'avatar,presenter', 'Paid', '2026-07-01 13:38:33', 'elai.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Colossyan', 'AI video generator with digital presenters.', 'Video Generation', 'https://www.colossyan.com', 'video,avatar', 'Paid', '2026-07-01 13:38:33', 'colossyan.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Hour One', 'Generate videos using AI humans.', 'Video Generation', 'https://hourone.ai', 'avatar,video', 'Paid', '2026-07-01 13:38:33', 'hourone.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('GitHub Copilot', 'AI coding assistant inside IDEs.', 'Coding', 'https://github.com/features/copilot', 'coding,developer', 'Paid', '2026-07-01 13:38:33', 'github-copilot.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Cursor', 'AI-powered code editor.', 'Coding', 'https://cursor.com', 'coding,editor', 'Freemium', '2026-07-01 13:38:33', 'cursor.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Tabnine', 'AI code completion assistant.', 'Coding', 'https://www.tabnine.com', 'coding,autocomplete', 'Freemium', '2026-07-01 13:38:33', 'tabnine.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Amazon Q Developer', 'AI coding assistant from AWS.', 'Coding', 'https://aws.amazon.com/q/developer', 'coding,aws', 'Free', '2026-07-01 13:38:33', 'amazon-q.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Replit AI', 'AI coding assistant in Replit IDE.', 'Coding', 'https://replit.com', 'coding,replit', 'Freemium', '2026-07-01 13:38:33', 'replit.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Blackbox AI', 'AI assistant for programmers.', 'Coding', 'https://www.blackbox.ai', 'coding,developer', 'Freemium', '2026-07-01 13:38:33', 'blackbox.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Sourcegraph Cody', 'AI coding assistant for repositories.', 'Coding', 'https://sourcegraph.com/cody', 'coding,search', 'Freemium', '2026-07-01 13:38:33', 'cody.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Continue', 'Open-source AI coding assistant.', 'Coding', 'https://continue.dev', 'coding,open-source', 'Open Source', '2026-07-01 13:38:33', 'continue.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Windsurf', 'AI-native IDE for developers.', 'Coding', 'https://windsurf.com', 'coding,editor', 'Freemium', '2026-07-01 13:38:33', 'windsurf.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Bolt.new', 'Build full-stack apps using AI prompts.', 'Coding', 'https://bolt.new', 'webapp,developer', 'Freemium', '2026-07-01 13:38:33', 'bolt.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Lovable', 'Create web apps using natural language.', 'Coding', 'https://lovable.dev', 'website,app', 'Freemium', '2026-07-01 13:38:33', 'lovable.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('v0', 'Generate UI components using AI.', 'Coding', 'https://v0.dev', 'ui,react', 'Freemium', '2026-07-01 13:38:33', 'v0.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Devin', 'AI software engineer by Cognition.', 'Coding', 'https://devin.ai', 'developer,automation', 'Paid', '2026-07-01 13:38:33', 'devin.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Phind', 'AI search engine for developers.', 'Coding', 'https://www.phind.com', 'coding,search', 'Freemium', '2026-07-01 13:38:33', 'phind.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Mintlify AI', 'AI documentation generator.', 'Developer', 'https://mintlify.com', 'documentation,developer', 'Freemium', '2026-07-01 13:38:33', 'mintlify.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Pieces for Developers', 'AI productivity tool for developers.', 'Developer', 'https://pieces.app', 'developer,productivity', 'Freemium', '2026-07-01 13:38:33', 'pieces.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Warp AI', 'AI-powered terminal for developers.', 'Developer', 'https://www.warp.dev', 'terminal,developer', 'Freemium', '2026-07-01 13:38:33', 'warp.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('AskCodi', 'AI coding assistant for multiple languages.', 'Coding', 'https://www.askcodi.com', 'coding,assistant', 'Freemium', '2026-07-01 13:38:33', 'askcodi.png');
INSERT INTO ai_tools (name, description, category, url, tags, pricing, created_at, logo) VALUES ('Qodo', 'AI code review, testing, and coding assistant.', 'Coding', 'https://www.qodo.ai', 'testing,developer', 'Freemium', '2026-07-01 13:38:33', 'qodo.png');
